// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzulokHangjaBE.Data;

namespace SzulokHangjaBE.Migrations
{
    [DbContext(typeof(SzulokHangjaBEContext))]
    [Migration("20200210234538_InitializeDB")]
    partial class InitializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.ParentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeOfChild")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewType")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentPost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a24f85ba-2dac-41ba-b1d0-6c31dee5f642"),
                            AgeOfChild = 8,
                            Location = "ParentPost1",
                            ReviewTopic = "Eszkoztar",
                            ReviewType = false,
                            Text = "nezzetek ma milyen fikas a pad",
                            Title = "Szarok a padok a suliban"
                        },
                        new
                        {
                            Id = new Guid("9e6dfb96-8530-49fd-99b9-0e5ca9df6942"),
                            AgeOfChild = 13,
                            Location = "ParentPost2",
                            ReviewTopic = "NAT",
                            ReviewType = true,
                            Text = "vegre olvassak mar a 50shds of greyt altalanosban",
                            Title = "Szuper jo az uj irodalom tanterv"
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewType")
                        .HasColumnType("bit");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherPost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0f51189-6ca7-45ce-ac85-ae8fd4cddd46"),
                            Location = "TeacherPost",
                            ReviewTopic = "NAT",
                            ReviewType = true,
                            Salary = 1333333,
                            Text = "vegre olvassak mar a 50shds of greyt altalanosban",
                            Title = "Szuper jo az uj irodalom tanterv"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
