// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzulokHangjaBE.Data;

namespace SzulokHangjaBE.Migrations
{
    [DbContext(typeof(SzulokHangjaBEContext))]
    [Migration("20200213075740_migrancs")]
    partial class migrancs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.ParentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PositiveMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ParentPost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75dee788-32a5-46fe-a743-35f9735c0272"),
                            CommentType = 1,
                            Location = "Budapest",
                            Message = "Ninncs helyettesítés betegség idején",
                            PositiveMessage = false,
                            SubmissionDate = new DateTime(2020, 2, 13, 8, 57, 40, 373, DateTimeKind.Local).AddTicks(2479)
                        },
                        new
                        {
                            Id = new Guid("b882cd95-fee7-4145-8a6f-a114909b3559"),
                            CommentType = 0,
                            Location = "Vas",
                            Message = "Szuper jo az uj irodalom tanterv",
                            PositiveMessage = true,
                            SubmissionDate = new DateTime(2020, 2, 13, 8, 57, 40, 376, DateTimeKind.Local).AddTicks(5366)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostRecommendation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cad1581-8923-4f07-825e-38cadac8ebe4"),
                            Location = "Zala",
                            Name = "Maris",
                            Recommendation = "Több szabadságot a tanároknak",
                            SubmissionDate = new DateTime(2020, 2, 13, 8, 57, 40, 376, DateTimeKind.Local).AddTicks(6517)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Workload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostSalary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf5db75f-6c25-4b43-9a15-18a662de5b6d"),
                            Experience = "10 éve tanítok irodalmat és történelmet",
                            Location = "Bekes",
                            Name = "Ili",
                            Salary = 250000,
                            SubmissionDate = new DateTime(2020, 2, 13, 8, 57, 40, 376, DateTimeKind.Local).AddTicks(7926),
                            Workload = "Heti 38 óra plusz helyettesítések"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
