// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzulokHangjaBE.Data;

namespace SzulokHangjaBE.Migrations
{
    [DbContext(typeof(SzulokHangjaBEContext))]
    [Migration("20200213224417_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.ParentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PositiveMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ParentPost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4b160e5-bc68-4a04-a5d5-fb2496584373"),
                            CommentType = 1,
                            Location = "Budapest",
                            Message = "Ninncs helyettesítés betegség idején",
                            PositiveMessage = false,
                            SubmissionDate = new DateTime(2020, 2, 13, 23, 44, 17, 15, DateTimeKind.Local).AddTicks(5120)
                        },
                        new
                        {
                            Id = new Guid("eaab5f2a-2f85-4be4-9ecb-f7db52a57fcb"),
                            CommentType = 0,
                            Location = "Vas",
                            Message = "Szuper jo az uj irodalom tanterv",
                            PositiveMessage = true,
                            SubmissionDate = new DateTime(2020, 2, 13, 23, 44, 17, 18, DateTimeKind.Local).AddTicks(5159)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostRecommendation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("078c03b0-5beb-4315-96b1-9af2320afe19"),
                            Location = "Zala",
                            Name = "Maris",
                            Recommendation = "Több szabadságot a tanároknak",
                            SubmissionDate = new DateTime(2020, 2, 13, 23, 44, 17, 18, DateTimeKind.Local).AddTicks(5673)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Workload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostSalary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5436537-918a-4047-8c58-c6c55c666f36"),
                            Experience = "5 éve tanítok irodcdccdcdcdcdcdcdcdcdcdcdcdcddcds történelmet",
                            Location = "Bekes",
                            Name = "Ili",
                            Salary = 250000,
                            SubmissionDate = new DateTime(2020, 2, 13, 23, 44, 17, 18, DateTimeKind.Local).AddTicks(6635),
                            Workload = "Heti 38 óra plusz helyettesítések"
                        },
                        new
                        {
                            Id = new Guid("1607bbde-6a2e-40f7-b020-8b6f88f3d9a8"),
                            Experience = "10 éve tanítok irodalmat és történelmet",
                            Location = "Pjost",
                            Name = "Zsuzs",
                            Salary = 2232323,
                            SubmissionDate = new DateTime(2020, 2, 13, 23, 44, 17, 18, DateTimeKind.Local).AddTicks(7577),
                            Workload = "Heti 38 óra plusz helyettesítések"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
