// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzulokHangjaBE.Data;

namespace SzulokHangjaBE.Migrations
{
    [DbContext(typeof(SzulokHangjaBEContext))]
    partial class SzulokHangjaBEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.SuperPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewType")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperPost");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SuperPost");
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.ParentPost", b =>
                {
                    b.HasBaseType("SzulokHangjaBE.Models.UserPosts.SuperPost");

                    b.Property<int>("AgeOfChild")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ParentPost");
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPost", b =>
                {
                    b.HasBaseType("SzulokHangjaBE.Models.UserPosts.SuperPost");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TeacherPost");
                });
#pragma warning restore 612, 618
        }
    }
}
