// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzulokHangjaBE.Data;

namespace SzulokHangjaBE.Migrations
{
    [DbContext(typeof(SzulokHangjaBEContext))]
    partial class SzulokHangjaBEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.ParentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PositiveMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ParentPost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35dab522-7a94-4b9a-aef6-c55b3420d4eb"),
                            CommentType = 1,
                            Location = "Budapest",
                            Message = "Ninncs helyettesítés betegség idején",
                            PositiveMessage = false,
                            SubmissionDate = new DateTime(2020, 2, 13, 14, 45, 35, 953, DateTimeKind.Local).AddTicks(9064)
                        },
                        new
                        {
                            Id = new Guid("79ddedbf-676d-47aa-966c-cdb03c1120c6"),
                            CommentType = 0,
                            Location = "Vas",
                            Message = "Szuper jo az uj irodalom tanterv",
                            PositiveMessage = true,
                            SubmissionDate = new DateTime(2020, 2, 13, 14, 45, 35, 957, DateTimeKind.Local).AddTicks(2988)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostRecommendation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15002386-cca1-4bda-b772-c8f70cfb20e1"),
                            Location = "Zala",
                            Name = "Maris",
                            Recommendation = "Több szabadságot a tanároknak",
                            SubmissionDate = new DateTime(2020, 2, 13, 14, 45, 35, 957, DateTimeKind.Local).AddTicks(3735)
                        });
                });

            modelBuilder.Entity("SzulokHangjaBE.Models.UserPosts.TeacherPostSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Workload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherPostSalary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7be0359f-7035-4019-ae80-db2283685cdd"),
                            Experience = "10 éve tanítok irodalmat és történelmet",
                            Location = "Bekes",
                            Name = "Ili",
                            Salary = 250000,
                            SubmissionDate = new DateTime(2020, 2, 13, 14, 45, 35, 957, DateTimeKind.Local).AddTicks(5197),
                            Workload = "Heti 38 óra plusz helyettesítések"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
